name: Build and deploy Node.js app to Azure Web App - docker-monitoring-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies in backend
        run: |
          cd backend  # Navigate to the backend folder
          npm install  # Install dependencies for the backend
          npm run build --if-present  # Optional, if you have build steps
          npm run test --if-present  # Optional, if you have tests

      - name: Zip artifact for deployment
        run: |
          cd backend  # Navigate to the backend folder
          zip -r release.zip .  # Zip the contents of the backend folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/release.zip  # Upload the zipped artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip  # Unzip the release artifact

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docker-monitoring-backend'  # Your Azure App Service name
          slot-name: 'Production'  # Your deployment slot, change if needed
          package: .  # Deploy the current directory (unzipped backend contents)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D9089E4F27064F69BEC11C44D1A29E54 }}  # Your Azure publish profile secret
